### PR TITLE
band aid fix if `sun.reflect.Reflection` cant be found

### PR DESCRIPTION
**Pull request by AnAwesomGuy**
note that i didnt test this and made it in the web interface

### CODE REVIEW

**Comment by Caedis** [comment]
Got any error logs for the reason for this?
NoClassDefFoundError is handled by the Exception catch all

**Comment by Glease** [comment]
@Caedis Error is not a subclass of Exception

**Comment by AnAwesomGuy** [comment]
> Got any error logs for the reason for this? NoClassDefFoundError is handled by the Exception catch all

what Glease said, and also `sun.reflect.Reflection` doesnt exist on all jdks
this is also just a bandaid fix, something better would be for hodgepodge to patch this to work on java 8+ by using `StackWalker`

**Comment by Caedis** [comment]
Good to know. I swear i remember seeing an instanceof check for NoClassDefFoundError inside of a general Exception catch recently. Maybe that was checking the cause of the exception

**Comment by Caedis** [comment]
Nope, i was not blind, just misread it as NoClassDefFoundError
https://github.com/GTNewHorizons/waila/pull/21/files#diff-6f4641a226bd5d2f3ff7cd36e29db8f339dbaed34d46ae1bfc4bc185a91887b0R87-R92

**Comment by Dream-Master** [comment]
@AnAwesomGuy @Glease @Caedis any news here ?

**Review by eigenraven — APPROVED** [review]

**Pull request merged**
